name: saa_mobile
description: 'Sun* Annual Awards Mobile Application'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  supabase_flutter: ^2.8.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  slang_build_runner: ^3.31.0
  mocktail: ^1.0.4
  flutter_gen_runner: ^5.7.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    - assets/awards/awards/
    - assets/awards/hero_tier/

  fonts:
    - family: DigitalNumbers
      fonts:
        - asset: assets/fonts/DigitalNumbers-Regular.ttf
          weight: 400
